<a href="https://colab.research.google.com/github/Yashchauhan23/Deep_Learning/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

Sentences

In [2]:
sent = [ 'the glass of milk', 
        'the glass of juice', 
        'the cup of tea',
        ' I am a good boy',
        'I am a good developer',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 ' I am a good boy',
 'I am a good developer',
 'your videos are good']

Vocabulary size


In [4]:
voc_size=10000

In [6]:
onehot_repr = [one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[288, 3135, 4890, 8686], [288, 3135, 4890, 9704], [288, 7322, 4890, 1190], [2116, 6130, 9703, 203, 1580], [2116, 6130, 9703, 203, 8937], [7158, 8673, 8004, 203]]


Word Embedding Representation


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding= 'pre',maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0  288 3135 4890 8686]
 [   0    0    0    0  288 3135 4890 9704]
 [   0    0    0    0  288 7322 4890 1190]
 [   0    0    0 2116 6130 9703  203 1580]
 [   0    0    0 2116 6130 9703  203 8937]
 [   0    0    0    0 7158 8673 8004  203]]


In [10]:
dim=10

In [11]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

[[[ 0.01363343 -0.01940206  0.04615753  0.01758805  0.02991783
    0.02281601 -0.01080334 -0.04397653  0.03447986 -0.04396585]
  [ 0.01363343 -0.01940206  0.04615753  0.01758805  0.02991783
    0.02281601 -0.01080334 -0.04397653  0.03447986 -0.04396585]
  [ 0.01363343 -0.01940206  0.04615753  0.01758805  0.02991783
    0.02281601 -0.01080334 -0.04397653  0.03447986 -0.04396585]
  [ 0.01363343 -0.01940206  0.04615753  0.01758805  0.02991783
    0.02281601 -0.01080334 -0.04397653  0.03447986 -0.04396585]
  [-0.0388425   0.04318954  0.00425519  0.00789852  0.04023034
   -0.01573874  0.04768315  0.03009215  0.04308471  0.00881363]
  [-0.02967088  0.01599493  0.0272903   0.04615517 -0.01035235
    0.0194951  -0.03151293 -0.04153911  0.02608417  0.00189395]
  [-0.0164305   0.04889828 -0.0071309   0.01748011 -0.00879632
    0.04624769 -0.03682502  0.02810903 -0.01773834 -0.00407026]
  [ 0.02010187 -0.03356589 -0.0369341  -0.00559581 -0.00628342
   -0.01031049  0.00110747  0.02171112  0.041068

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,  288, 3135, 4890, 8686], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

[[ 0.01363343 -0.01940206  0.04615753  0.01758805  0.02991783  0.02281601
  -0.01080334 -0.04397653  0.03447986 -0.04396585]
 [ 0.01363343 -0.01940206  0.04615753  0.01758805  0.02991783  0.02281601
  -0.01080334 -0.04397653  0.03447986 -0.04396585]
 [ 0.01363343 -0.01940206  0.04615753  0.01758805  0.02991783  0.02281601
  -0.01080334 -0.04397653  0.03447986 -0.04396585]
 [ 0.01363343 -0.01940206  0.04615753  0.01758805  0.02991783  0.02281601
  -0.01080334 -0.04397653  0.03447986 -0.04396585]
 [-0.0388425   0.04318954  0.00425519  0.00789852  0.04023034 -0.01573874
   0.04768315  0.03009215  0.04308471  0.00881363]
 [-0.02967088  0.01599493  0.0272903   0.04615517 -0.01035235  0.0194951
  -0.03151293 -0.04153911  0.02608417  0.00189395]
 [-0.0164305   0.04889828 -0.0071309   0.01748011 -0.00879632  0.04624769
  -0.03682502  0.02810903 -0.01773834 -0.00407026]
 [ 0.02010187 -0.03356589 -0.0369341  -0.00559581 -0.00628342 -0.01031049
   0.00110747  0.02171112  0.04106832  0.0250074 ]]
